// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUMbzYV6d-Jjh2L-Wauus7ymi2MH_4fRo',
    appId: '1:964454806711:web:c9ede0ca28a114a1ab0932',
    messagingSenderId: '964454806711',
    projectId: 'hdims-699e0',
    authDomain: 'hdims-699e0.firebaseapp.com',
    storageBucket: 'hdims-699e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuTBSxTIzQcUa3_5ED7uiHOzWI_cf8uH4',
    appId: '1:964454806711:android:702027561d0de715ab0932',
    messagingSenderId: '964454806711',
    projectId: 'hdims-699e0',
    storageBucket: 'hdims-699e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfzokaYiR4mFZ3ux9AmCK_COf97UvSDxY',
    appId: '1:964454806711:ios:df9e2668fd159595ab0932',
    messagingSenderId: '964454806711',
    projectId: 'hdims-699e0',
    storageBucket: 'hdims-699e0.firebasestorage.app',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfzokaYiR4mFZ3ux9AmCK_COf97UvSDxY',
    appId: '1:964454806711:ios:df9e2668fd159595ab0932',
    messagingSenderId: '964454806711',
    projectId: 'hdims-699e0',
    storageBucket: 'hdims-699e0.firebasestorage.app',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUMbzYV6d-Jjh2L-Wauus7ymi2MH_4fRo',
    appId: '1:964454806711:web:09b7ee349543f0dcab0932',
    messagingSenderId: '964454806711',
    projectId: 'hdims-699e0',
    authDomain: 'hdims-699e0.firebaseapp.com',
    storageBucket: 'hdims-699e0.firebasestorage.app',
  );
}
