// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD70H8dS400seIy56Asgq9TU8l_2TO9GE',
    appId: '1:836255283607:web:5e195eadb590e0e8192cd2',
    messagingSenderId: '836255283607',
    projectId: 'hdimss-c0668',
    authDomain: 'hdimss-c0668.firebaseapp.com',
    storageBucket: 'hdimss-c0668.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzod_sWeD8l9JyczWlGO5okDzZ2BPlrms',
    appId: '1:836255283607:android:8688cdc89c0f2372192cd2',
    messagingSenderId: '836255283607',
    projectId: 'hdimss-c0668',
    storageBucket: 'hdimss-c0668.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY9YaCxnPVraqcqbniyGA91lOW34m9-kI',
    appId: '1:836255283607:ios:08e2b254e3ab8be2192cd2',
    messagingSenderId: '836255283607',
    projectId: 'hdimss-c0668',
    storageBucket: 'hdimss-c0668.firebasestorage.app',
    iosBundleId: 'com.example.hdimss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY9YaCxnPVraqcqbniyGA91lOW34m9-kI',
    appId: '1:836255283607:ios:08e2b254e3ab8be2192cd2',
    messagingSenderId: '836255283607',
    projectId: 'hdimss-c0668',
    storageBucket: 'hdimss-c0668.firebasestorage.app',
    iosBundleId: 'com.example.hdimss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD70H8dS400seIy56Asgq9TU8l_2TO9GE',
    appId: '1:836255283607:web:4192cbb77e30c279192cd2',
    messagingSenderId: '836255283607',
    projectId: 'hdimss-c0668',
    authDomain: 'hdimss-c0668.firebaseapp.com',
    storageBucket: 'hdimss-c0668.firebasestorage.app',
  );
}
