// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHJpkKEJ8Uw2FcPwzQqUf5ZEzjRweDQ8Y',
    appId: '1:784503341281:web:0ce9d44f49e423043b37a0',
    messagingSenderId: '784503341281',
    projectId: 'hdimrs',
    authDomain: 'hdimrs.firebaseapp.com',
    storageBucket: 'hdimrs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8jygf_QIrzPtd9uWUcwkUD_6IST1TixU',
    appId: '1:784503341281:android:c81727639de933f33b37a0',
    messagingSenderId: '784503341281',
    projectId: 'hdimrs',
    storageBucket: 'hdimrs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBOo5HylIQ-GP_xuYIQ-wZHywrIIrEBiw',
    appId: '1:784503341281:ios:5d8b9625626f838b3b37a0',
    messagingSenderId: '784503341281',
    projectId: 'hdimrs',
    storageBucket: 'hdimrs.firebasestorage.app',
    iosBundleId: 'com.example.hdimss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBOo5HylIQ-GP_xuYIQ-wZHywrIIrEBiw',
    appId: '1:784503341281:ios:5d8b9625626f838b3b37a0',
    messagingSenderId: '784503341281',
    projectId: 'hdimrs',
    storageBucket: 'hdimrs.firebasestorage.app',
    iosBundleId: 'com.example.hdimss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHJpkKEJ8Uw2FcPwzQqUf5ZEzjRweDQ8Y',
    appId: '1:784503341281:web:20595728d3435d193b37a0',
    messagingSenderId: '784503341281',
    projectId: 'hdimrs',
    authDomain: 'hdimrs.firebaseapp.com',
    storageBucket: 'hdimrs.firebasestorage.app',
  );

}